name: CI Pipeline

on:
  push:
    branches:
      - main
      - '**' ##qualquer branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest ##onde roda

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: lista o repositorio
        run: ls -la

      - name: Set environment variable
        run: echo "MY_VARIABLE=Hello" >> $GITHUB_ENV

      - name: Display environment variable
        run: echo $MY_VARIABLE

      - name: Run a sample script
        run: |
          echo "Running build..."
          echo "The value of MY_VARIABLE is $MY_VARIABLE"

      - name: Display the environment variable
        run: echo "The value of MY_VARIABLE is ${{ secrets.TESTE_VARIAVEL }}"
